[workspace]
name = "config-facilitator"
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[dependencies]
go = ">=1.24.4,<1.25"

[tasks]
test = "go test ./..."
build = "go build ./..."
help = "go run ./cmd/cfgfc --help"
usr-install = "go build -o ~/.local/bin/cfgfc ./cmd/cfgfc"
global-install = "go build -o cfgfc && sudo mv cfgfc /usr/local/bin/"