[workspace]
name = "config-facilitator"
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[dependencies]
go = ">=1.24.4,<1.25"

[tasks]
test = "go test ./..."
build = "go build ./..."
help = "go run ./cmd/cfgfc --help"
